'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace HostToHost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsDepositosClientesETVSoap", [Namespace]:="http://banorte.com/")>  _
    Partial Public Class wsDepositosClientesETV
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RecibirArchivosDepositosTXTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Modulo_Proceso.My.MySettings.Default.Modulo_Proceso_HostToHost_wsDepositosClientesETV
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RecibirArchivosDepositosTXTCompleted As RecibirArchivosDepositosTXTCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://banorte.com/RecibirArchivosDepositosTXT", RequestNamespace:="http://banorte.com/", ResponseNamespace:="http://banorte.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecibirArchivosDepositosTXT(ByVal ClaveUsuario As String, ByVal NombreArchivosDepositos As String, ByVal ArchivoDeposito As String, ByVal NombreArchivoCheques As String, ByVal ArchivoCheques As String) As ClsDepositoEstatus
            Dim results() As Object = Me.Invoke("RecibirArchivosDepositosTXT", New Object() {ClaveUsuario, NombreArchivosDepositos, ArchivoDeposito, NombreArchivoCheques, ArchivoCheques})
            Return CType(results(0),ClsDepositoEstatus)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecibirArchivosDepositosTXTAsync(ByVal ClaveUsuario As String, ByVal NombreArchivosDepositos As String, ByVal ArchivoDeposito As String, ByVal NombreArchivoCheques As String, ByVal ArchivoCheques As String)
            Me.RecibirArchivosDepositosTXTAsync(ClaveUsuario, NombreArchivosDepositos, ArchivoDeposito, NombreArchivoCheques, ArchivoCheques, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecibirArchivosDepositosTXTAsync(ByVal ClaveUsuario As String, ByVal NombreArchivosDepositos As String, ByVal ArchivoDeposito As String, ByVal NombreArchivoCheques As String, ByVal ArchivoCheques As String, ByVal userState As Object)
            If (Me.RecibirArchivosDepositosTXTOperationCompleted Is Nothing) Then
                Me.RecibirArchivosDepositosTXTOperationCompleted = AddressOf Me.OnRecibirArchivosDepositosTXTOperationCompleted
            End If
            Me.InvokeAsync("RecibirArchivosDepositosTXT", New Object() {ClaveUsuario, NombreArchivosDepositos, ArchivoDeposito, NombreArchivoCheques, ArchivoCheques}, Me.RecibirArchivosDepositosTXTOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecibirArchivosDepositosTXTOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecibirArchivosDepositosTXTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecibirArchivosDepositosTXTCompleted(Me, New RecibirArchivosDepositosTXTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://banorte.com/")>  _
    Partial Public Class ClsDepositoEstatus
        
        Private iEstatusField As EnumEstatusArchivoDeposito
        
        Private sDescripcionEstatusField As String
        
        Private sMensajeSalidaField As String
        
        Private sMensajeErrorField As String
        
        '''<remarks/>
        Public Property iEstatus() As EnumEstatusArchivoDeposito
            Get
                Return Me.iEstatusField
            End Get
            Set
                Me.iEstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sDescripcionEstatus() As String
            Get
                Return Me.sDescripcionEstatusField
            End Get
            Set
                Me.sDescripcionEstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sMensajeSalida() As String
            Get
                Return Me.sMensajeSalidaField
            End Get
            Set
                Me.sMensajeSalidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sMensajeError() As String
            Get
                Return Me.sMensajeErrorField
            End Get
            Set
                Me.sMensajeErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://banorte.com/")>  _
    Public Enum EnumEstatusArchivoDeposito
        
        '''<remarks/>
        RechazadoEnvio
        
        '''<remarks/>
        PendienteParaPrecarga
        
        '''<remarks/>
        PreCarga
        
        '''<remarks/>
        RechazadoPrecarga
        
        '''<remarks/>
        Pendiente
        
        '''<remarks/>
        Aceptado
        
        '''<remarks/>
        Cancelado
        
        '''<remarks/>
        CorreoEnviado
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub RecibirArchivosDepositosTXTCompletedEventHandler(ByVal sender As Object, ByVal e As RecibirArchivosDepositosTXTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecibirArchivosDepositosTXTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ClsDepositoEstatus
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClsDepositoEstatus)
            End Get
        End Property
    End Class
End Namespace
